### ISSUE TITLE
请问如何使用burp对PC微信小程序抓包？

### ISSUE THREAD

**Issue by MallocInfinity** [djerryz/Sheep_Sheep_Ni#1]
rt，我已经检索了Google前十页内容，没有得到解决

**Comment by djerryz** [comment]
1. taskmgr
2. 定位位置
![image](https://user-images.githubusercontent.com/24947060/190400215-874de2ff-4052-4c52-b04e-24a9517c612c.png)

3. 使用ProxifierPE的程序代理功能
* 配置proxy server到BP监听端口
* 配置Application rule到先前找到的程序位置

enjoy!

**Comment by MallocInfinity** [comment]
Thank you very much!
