### ISSUE TITLE
这个MatchPlayInfo看了半天代码没搞懂怎么算的，但是想了个笨方法竟然还能通关加次数

### ISSUE THREAD

**Issue by oyjx666** [djerryz/Sheep_Sheep_Ni#12]
看了半天怎么算MatchPlayInfo，一脸懵，后面想了个笨方法，就是改地图里的blockTypeData，只留一种图案，然后花几分钟通过了，并且是有通关记录的，没被识别作弊。没看完源码，不知道图案随机的算法是啥，但感觉它服务器端压根不管这个，MatchPlayInfo貌似是只会记录用户点击那些位置及层级的牌，到服务器端和它当天的关卡地图做校验，牌上面什么图案它不管，不知道后续官方会不会优化这个。另外它那个换装接口加次数是还没修复吗，现在好像还有这个bug😂😂😂

**Comment by lileixuan** [comment]
这个咋么用啊？

**Comment by wulasite** [comment]
blockTypeData是在哪里的参数

**Comment by BugMaker888** [comment]
[《羊了个羊》作弊教程四：草了个草](https://bugmaker.eth.limo/sheep_made_a_sheep_all_glass.html)

**Comment by jiabuda** [comment]
> 看了半天怎么算MatchPlayInfo，一脸懵，后面想了个笨方法，就是改地图里的blockTypeData，只留一种图案，然后花几分钟通过了，并且是有通关记录的，没被识别作弊。没看完源码，不知道图案随机的算法是啥，但感觉它服务器端压根不管这个，MatchPlayInfo貌似是只会记录用户点击那些位置及层级的牌，到服务器端和它当天的关卡地图做校验，牌上面什么图案它不管，不知道后续官方会不会优化这个。另外它那个换装接口加次数是还没修复吗，现在好像还有这个bug😂😂😂

应该服务器管不了点击位置的吧，这样的话，服务器压力会非常大

**Comment by djerryz** [comment]
Blocktype和seed不参与最后的结果运算，close
