### ISSUE TITLE
ApiPost 请求无法获取

### ISSUE THREAD

**Issue by ttcoder404** [djerryz/Sheep_Sheep_Ni#2]
![](https://github.com/ttcoder404/Awesome-CV-Review/blob/main/images/QQ%E6%88%AA%E5%9B%BE20220917071233.png)

**Comment by ttcoder404** [comment]
![0917071233](https://user-images.githubusercontent.com/10204344/190830238-7012f018-b592-4a77-a715-77a9f30f8996.png)

**Comment by djerryz** [comment]
首先，这个接口吐的数据比较大，响应时间超过10秒以上，考虑超时设置导致的请求失败。
其次，/admin/ 应属于管理员控制级接口，羊了个羊应该不打算在生成环境放出来以供调用，有可能这部分接口已经下线，或者已加上了鉴权机制，请自行确认。

**Comment by djerryz** [comment]
刚刚测试发现接口返回的数据内容为"成功.."不再是全部地图信息，应该是作者进行了修改，但仍可以通过获取挑战接口，通过枚举挑战ID的形式获取全部地图信息。
