### ISSUE TITLE
学习讨论，请教是怎么得到小程序前端代码的

### ISSUE THREAD

**Issue by seamusopen** [djerryz/Sheep_Sheep_Ni#3]
想讨教一下是怎么获取到前端代码的
解包wxapkg吗

**Comment by L1f3-15-a-kn1f3** [comment]
我没拿到前端代码，仅仅是抓包找对应请求的接口

**Comment by djerryz** [comment]
是的，吾爱破解和公众号有很多优秀的文章可以参考

**Comment by djerryz** [comment]
1. 访问: C:\Users\你的用户名\Documents\WeChat Files\Applet\
2. UnpackMiniApp.exe 解密下  `Applet\wxdXXXXXXXX\20\__APP__.wxapkg`  （wxdXXXXXXXX根据小程序的实际情况)
3. 拿到解密后的 wxpack ，打开 mp-unpack 选择解包， 点击导出，即可
enjoy!

**Comment by rxxy** [comment]
请问目录中没有生成wxapkg文件是什么原因呢。
大概是这样的目录
![image](https://user-images.githubusercontent.com/14834156/191309535-c123c0d1-e91a-4413-a00f-8ab13f1629d7.png)
