### ISSUE TITLE
能通过接口修改道具次数吗

### ISSUE THREAD

**Issue by Cosinhs** [djerryz/Sheep_Sheep_Ni#4]

**Comment by rslywhj** [comment]
逻辑写在前端里

**Comment by djerryz** [comment]
@rslywhj 的回答比较准确，可以看到通过接口下发数据到前端后，道具的操作实际没有触发任何网络动作

相当于道具执行的逻辑仅仅是打乱存储在变量中的map_data，因此是纯前端的行为哈
