### ISSUE TITLE
皮肤接口有消息吗

### ISSUE THREAD

**Issue by L1f3-15-a-kn1f3** [djerryz/Sheep_Sheep_Ni#6]
我只抓到了设置用户皮肤的接口，获取皮肤是在通关接口的skin字段吗

**Comment by BugMaker888** [comment]
[《羊了个羊》作弊教程二：解锁全皮肤](https://bugmaker.eth.limo/sheep_made_a_sheep_skin.html)

**Comment by djerryz** [comment]
参考 @BugMaker888 评论
